name: scaling_octo_couscous
description: Clean Architecture based project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  dotenv: ^4.2.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^12.1.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.5
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
